# -*- coding: utf-8 -*-
"""
/***************************************************************************
 zrf
                                 A QGIS plugin
 fh
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-29
        copyright            : (C) 2025 by fghfgh
        email                : jfhj
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'fghfgh'
__date__ = '2025-03-29'
__copyright__ = '(C) 2025 by fghfgh'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load zrf class from file zrf.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fgh import zrfPlugin
    return zrfPlugin()
